const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  loadExample: (key) => ipcRenderer.invoke('load-example', key),
  getExamples: () => ipcRenderer.invoke('get-examples'),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  loadProjectFile: (dir, filename) => ipcRenderer.invoke('load-project-file', dir, filename),
  saveProjectFile: (dir, filename, content) => ipcRenderer.invoke('save-project-file', dir, filename, content),
  createFile: (dir, filename, content) => ipcRenderer.invoke('create-file', dir, filename, content),
  createFolder: (dir, folderName) => ipcRenderer.invoke('create-folder', dir, folderName),
  renameFile: (dir, oldName, newName) => ipcRenderer.invoke('rename-file', dir, oldName, newName),
  deleteFile: (filePath) => ipcRenderer.invoke('delete-file', filePath),
  showConfirm: (title, message) => ipcRenderer.invoke('show-confirm', title, message),
  showInput: (title, label, defaultValue) => ipcRenderer.invoke('show-input', title, label, defaultValue),
  listProjectFiles: (dir) => ipcRenderer.invoke('list-project-files', dir),
  scanProjectTree: (dir) => ipcRenderer.invoke('scan-project-tree', dir),
  createProject: (dir, name) => ipcRenderer.invoke('create-project', dir, name),
  buildProject: (dir, target) => ipcRenderer.invoke('build-project', dir, target),
  buildAndRunProject: (dir, target) => ipcRenderer.invoke('build-and-run-project', dir, target),
  buildWebPreview: (dir, projectName) => ipcRenderer.invoke('build-web-preview', dir, projectName),
  openWebPreview: (dir, projectName) => ipcRenderer.invoke('open-web-preview', dir, projectName),
  getPreviewInfo: (projectName) => ipcRenderer.invoke('get-preview-info', projectName),
  runBinary: (binaryPath) => ipcRenderer.invoke('run-binary', binaryPath),
  findBinary: (dir) => ipcRenderer.invoke('find-binary', dir),
  openBuildFolder: (dir) => ipcRenderer.invoke('open-build-folder', dir),
  showPrompt: (title, label, defaultValue) => ipcRenderer.invoke('show-prompt', title, label, defaultValue),
  getHomeDir: () => ipcRenderer.invoke('get-home-dir'),
  getBasename: (p) => ipcRenderer.invoke('get-basename', p),
  revealInFolder: (path) => ipcRenderer.invoke('reveal-in-folder', path),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  onMenuAction: (callback) => ipcRenderer.on('menu-action', (_event, action) => callback(action)),
  onRunOutput: (callback) => ipcRenderer.on('run-output', (_event, data) => callback(data)),
});
