plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.hello_world'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.hello_world"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }
    buildTypes {
        debug {
            debuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
