plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.feedback'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.feedback"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        sourceSets {
        main {
            assets.srcDirs("../../ui", "src/main/assets")
        }
    }

    externalNativeBuild {
            cmake {
                cppFlags ""
            }
        }
    }
    buildTypes {
        debug {
            debuggable true
        }
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.22.1"
        }
    }
}
