#!/usr/bin/env python3
"""
Compile Vulkan GLSL shaders to SPIR-V and generate a C header with
embedded uint32_t arrays.

Usage:
    python3 compile_vulkan_shaders.py <shader_dir> <output_header>

Requires glslangValidator or glslc on PATH.
"""

import os, sys, struct, subprocess, shutil

SHADERS = [
    ("shape.vert",  "aroma_vk_shape_vert_spv"),
    ("shape.frag",  "aroma_vk_shape_frag_spv"),
    ("text.vert",   "aroma_vk_text_vert_spv"),
    ("text.frag",   "aroma_vk_text_frag_spv"),
    ("image.vert",  "aroma_vk_image_vert_spv"),
    ("image.frag",  "aroma_vk_image_frag_spv"),
]

def find_compiler():
    for name in ["glslc", "glslangValidator"]:
        path = shutil.which(name)
        if path:
            return name, path
    return None, None

def compile_shader(compiler_name, compiler_path, glsl_path, spv_path):
    if compiler_name == "glslc":
        cmd = [compiler_path, glsl_path, "-o", spv_path]
    else:
        cmd = [compiler_path, "-V", glsl_path, "-o", spv_path]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"ERROR compiling {glsl_path}:\n{result.stderr}", file=sys.stderr)
        return False
    return True

def spv_to_c_array(spv_path, var_name):
    with open(spv_path, "rb") as f:
        data = f.read()
    # SPIR-V is 4-byte aligned uint32
    words = struct.unpack(f"<{len(data)//4}I", data)
    lines = []
    lines.append(f"static const uint32_t {var_name}[] = {{")
    row = []
    for i, w in enumerate(words):
        row.append(f"0x{w:08x}")
        if len(row) == 8:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <shader_dir> <output_header>")
        sys.exit(1)

    shader_dir = sys.argv[1]
    output = sys.argv[2]
    compiler_name, compiler_path = find_compiler()
    if not compiler_path:
        print("ERROR: No GLSL→SPIR-V compiler found (glslc or glslangValidator)", file=sys.stderr)
        sys.exit(1)

    header_parts = [
        "/* Auto-generated by compile_vulkan_shaders.py — DO NOT EDIT */",
        "#ifndef AROMA_VULKAN_SHADERS_H",
        "#define AROMA_VULKAN_SHADERS_H",
        "#include <stdint.h>",
        "",
    ]

    for glsl_name, var_name in SHADERS:
        glsl_path = os.path.join(shader_dir, glsl_name)
        spv_path = os.path.join(shader_dir, glsl_name.replace(".", "_") + ".spv")
        if not os.path.exists(glsl_path):
            print(f"ERROR: {glsl_path} not found", file=sys.stderr)
            sys.exit(1)
        print(f"Compiling {glsl_name} → {os.path.basename(spv_path)}")
        if not compile_shader(compiler_name, compiler_path, glsl_path, spv_path):
            sys.exit(1)
        header_parts.append(spv_to_c_array(spv_path, var_name))
        header_parts.append("")

    header_parts.append("#endif /* AROMA_VULKAN_SHADERS_H */")

    with open(output, "w") as f:
        f.write("\n".join(header_parts) + "\n")
    print(f"Generated {output}")

if __name__ == "__main__":
    main()
